<a href="https://colab.research.google.com/github/Alejandro-Casanova/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7,7)
print(random_tensor)

tensor([[0.8931, 0.0871, 0.6699, 0.9254, 0.5270, 0.1260, 0.3594],
        [0.1642, 0.2133, 0.6217, 0.0593, 0.7635, 0.8226, 0.4818],
        [0.7299, 0.7402, 0.8417, 0.5434, 0.5879, 0.2178, 0.8098],
        [0.4581, 0.6493, 0.9572, 0.9796, 0.2241, 0.5818, 0.9568],
        [0.7590, 0.2519, 0.2953, 0.7244, 0.1995, 0.3114, 0.9429],
        [0.1051, 0.6533, 0.8259, 0.4233, 0.9641, 0.7656, 0.3513],
        [0.1834, 0.2166, 0.3515, 0.1188, 0.2495, 0.2435, 0.0200]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
random_tensor_2 = torch.rand(1,7)

# Perform matrix multiplication 
random_tensor @ random_tensor_2.T


tensor([[1.5198],
        [2.3717],
        [2.8383],
        [3.2651],
        [1.9435],
        [2.9125],
        [0.9151]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
RANDOM_SEED = 0
torch.random.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
random_tensor_3 = torch.rand(7,7)
random_tensor_4 = torch.rand(1,7)

# Matrix multiply tensors
random_tensor_3 @ random_tensor_4.T


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [14]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = torch.device("cuda") if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_cuda_1 = torch.rand(size=(2,3)).to(device)
tensor_cuda_2 = torch.rand(size=(2,3)).to(device)

tensor_cuda_1, tensor_cuda_2


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
output_of_7 = torch.matmul(tensor_cuda_1, tensor_cuda_2.T)
print(output_of_7)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [30]:
# Find max
print(f"Maximum: {torch.max(output_of_7)}")

# Find min
print(f"Minimum: {output_of_7.min()}")

Maximum: 0.5617256760597229
Minimum: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [44]:
# Find arg max
print(f"Maximum: {torch.argmax(output_of_7)}")
print(f"Value: {torch.flatten(output_of_7)[torch.argmax(output_of_7)]}")

# Find arg min
print(f"Minimum: {output_of_7.argmin()}")

Maximum: 3
Value: 0.5617256760597229
Minimum: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [47]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_A = torch.rand(1,1,1,10)

# Remove single dimensions
tensor_B = tensor_A.squeeze()

# Print out tensors and their shapes
tensor_A, tensor_A.shape, tensor_B, tensor_B.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))